version: 2.1
orbs:
  aws-s3: circleci/aws-s3@volatile
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Build Distribution
          command: gradle distTar
      - aws-s3/copy:
          from: build/distributions/kafka-connect-mongo-*.tgz
          to: 's3://artifacts.reactioncommerce.com/kafka-connect-mongo'
          arguments: "--acl public-read"
