version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Build Distribution
          command: gradle distTar
      - run:
          name: Install S3 Uploader
          command: |
            url='https://github.com/matthew-andrews/s3up/releases/download/v1.0.5/s3up_linux_amd64'
            curl --silent --location --fail "${url}" > /tmp/s3up
            chmod 755 /tmp/s3up
      - run:
          name: Upload to S3
          command: |
            cd build/distributions
            /tmp/s3up --bucket artifacts.reactioncommerce.com --destination /kafka-connect-mongo kafka-connect-mongo-*.tgz
