---
version: '2'
services:
  kafka-connect-mongo:
    image: quay.io/sailxjx/kafka-connect-mongo
    network_mode: host
    environment:
      CONNECT_REST_PORT: 38084
      CONNECT_BOOTSTRAP_SERVERS: 127.0.0.1:39092